-- Exam Timetable Management System Database Schema
-- Created: 2026-01-10

-- Create Database
CREATE DATABASE IF NOT EXISTS exam_timetable;
USE exam_timetable;

-- Drop existing tables if they exist (for fresh setup)
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS conflicts;
DROP TABLE IF EXISTS surveillances;
DROP TABLE IF EXISTS examens;
DROP TABLE IF EXISTS inscriptions;
DROP TABLE IF EXISTS etudiants;
DROP TABLE IF EXISTS modules;
DROP TABLE IF EXISTS professeurs;
DROP TABLE IF EXISTS salles;
DROP TABLE IF EXISTS formations;
DROP TABLE IF EXISTS departements;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;

-- Users table
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'doyen', 'chef', 'prof', 'student') NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN DEFAULT TRUE,
    INDEX idx_email (email),
    INDEX idx_role (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Departments table (chef_id FK added later after professeurs table exists)
CREATE TABLE departements (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    chef_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Formations table
CREATE TABLE formations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    department_id INT NOT NULL,
    description TEXT,
    duration_months INT,
    number_of_groups INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departements(id) ON DELETE CASCADE,
    UNIQUE(name, department_id),
    INDEX idx_department_id (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Professors table (must be before modules due to foreign key)
CREATE TABLE professeurs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL UNIQUE,
    department_id INT NOT NULL,
    speciality VARCHAR(255),
    max_exams_per_day INT DEFAULT 3,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departements(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_department_id (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Add chef_id foreign key to departements now that professeurs exists
ALTER TABLE departements
ADD CONSTRAINT fk_departements_chef 
FOREIGN KEY (chef_id) REFERENCES professeurs(id) ON DELETE SET NULL;

-- Modules table
CREATE TABLE modules (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    formation_id INT NOT NULL,
    professeur_id INT NOT NULL,
    credit_hours INT,
    semester INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (formation_id) REFERENCES formations(id) ON DELETE CASCADE,
    FOREIGN KEY (professeur_id) REFERENCES professeurs(id) ON DELETE CASCADE,
    INDEX idx_code (code),
    INDEX idx_formation_id (formation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Students table
CREATE TABLE etudiants (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL UNIQUE,
    formation_id INT NOT NULL,
    student_number VARCHAR(50) NOT NULL UNIQUE,
    enrollment_date DATE,
    group_number INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (formation_id) REFERENCES formations(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_student_number (student_number),
    INDEX idx_formation_id (formation_id),
    INDEX idx_group_number (group_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Exam Rooms table
CREATE TABLE salles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    capacity INT NOT NULL,
    location VARCHAR(255),
    type ENUM('classroom', 'amphi', 'computer_lab') DEFAULT 'classroom',
    department_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departements(id) ON DELETE SET NULL,
    INDEX idx_name (name),
    INDEX idx_department_id (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Enrollments (Students in Modules) table
CREATE TABLE inscriptions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    student_id INT NOT NULL,
    module_id INT NOT NULL,
    enrollment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    grade DECIMAL(5, 2),
    status ENUM('active', 'completed', 'dropped') DEFAULT 'active',
    FOREIGN KEY (student_id) REFERENCES etudiants(id) ON DELETE CASCADE,
    FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE,
    UNIQUE(student_id, module_id),
    INDEX idx_student_id (student_id),
    INDEX idx_module_id (module_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Exams table
CREATE TABLE examens (
    id INT PRIMARY KEY AUTO_INCREMENT,
    module_id INT NOT NULL,
    formation_id INT,
    group_number INT NOT NULL DEFAULT 1,
    exam_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room_id INT NOT NULL,
    created_by INT,
    status ENUM('scheduled', 'in_progress', 'completed', 'cancelled') DEFAULT 'scheduled',
    accepted_by_chefdep BOOLEAN DEFAULT NULL,
    accepted_by_doyen BOOLEAN DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE,
    FOREIGN KEY (formation_id) REFERENCES formations(id) ON DELETE SET NULL,
    FOREIGN KEY (room_id) REFERENCES salles(id) ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE(module_id, group_number, exam_date, start_time),
    INDEX idx_exam_date (exam_date),
    INDEX idx_status (status),
    INDEX idx_module_id (module_id),
    INDEX idx_formation_id (formation_id),
    INDEX idx_room_id (room_id),
    INDEX idx_group_number (group_number),
    INDEX idx_accepted_chefdep (accepted_by_chefdep),
    INDEX idx_accepted_doyen (accepted_by_doyen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Exam Supervisions (Surveillances) table
CREATE TABLE surveillances (
    id INT PRIMARY KEY AUTO_INCREMENT,
    exam_id INT NOT NULL,
    prof_id INT NOT NULL,
    role ENUM('invigilator', 'reserve') DEFAULT 'invigilator',
    assigned_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    status ENUM('assigned', 'confirmed', 'completed', 'absent') DEFAULT 'assigned',
    FOREIGN KEY (exam_id) REFERENCES examens(id) ON DELETE CASCADE,
    FOREIGN KEY (prof_id) REFERENCES professeurs(id) ON DELETE CASCADE,
    UNIQUE(exam_id, prof_id),
    INDEX idx_exam_id (exam_id),
    INDEX idx_prof_id (prof_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Conflicts table
CREATE TABLE conflicts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    exam_id INT,
    conflict_type ENUM('student_overlap', 'prof_overload', 'room_capacity', 'time_conflict', 'prof_fairness') NOT NULL,
    description TEXT,
    severity ENUM('low', 'medium', 'high') DEFAULT 'medium',
    resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (exam_id) REFERENCES examens(id) ON DELETE CASCADE,
    INDEX idx_exam_id (exam_id),
    INDEX idx_conflict_type (conflict_type),
    INDEX idx_severity (severity),
    INDEX idx_resolved (resolved)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- insertion des departements
INSERT INTO departements (name, description) VALUES
('mathematique', 'departement mathematique'),
('informatique', 'departement informatique'),
('physique', 'departement physique'),
('chemie', 'departement chemie'),
('biologie', 'departement biologie'),
('giologie', 'departement giologie'),
('Géographie et de l’Aménagement du Territoire', 'departement Géographie et de l’Aménagement du Territoire');


-- insertion des formations
INSERT INTO formations (name, department_id, description, duration_months) VALUES
-- ================= MATHEMATIQUE (29) =================
('1 year licence - mathematique generale', 1, 'Formation de base en mathematiques', 6),
('1 year licence - analyse mathematique', 1, 'Analyse mathematique fondamentale', 6),
('1 year licence - algebre generale', 1, 'Algebre lineaire et abstraite', 6),
('1 year licence - statistiques', 1, 'Statistiques descriptives', 6),
('1 year licence - probabilites', 1, 'Introduction aux probabilites', 6),
('2 year licence - mathematique appliquee', 1, 'Applications mathematiques', 6),
('2 year licence - logique mathematique', 1, 'Logique et raisonnement', 6),
('2 year licence - calcul scientifique', 1, 'Calcul numerique', 6),
('2 year licence - equations differentielles', 1, 'Equations differentielles', 6),
('2 year licence - methodes numeriques', 1, 'Methodes numeriques', 6),
('3 year licence - mathematiques avancees', 1, 'Approfondissement mathematique', 6),
('3 year licence - topologie', 1, 'Topologie generale', 6),
('3 year licence - optimisation', 1, 'Optimisation mathematique', 6),
('master - mathematiques pures', 1, 'Mathematiques theoriques', 6),
('master - mathematiques appliquees', 1, 'Mathematiques appliquees', 6),
('master - statistiques avancees', 1, 'Statistiques avancees', 6),
('master - probabilites avancees', 1, 'Probabilites approfondies', 6),
('master - finance mathematique', 1, 'Finance quantitative', 6),
('doctorat - mathematiques', 1, 'Recherche en mathematiques', 6),
('doctorat - analyse', 1, 'Analyse mathematique', 6),
('doctorat - algebre', 1, 'Recherche en algebre', 6),
('certificat - mathematique pour ingenieurs', 1, 'Mathematique appliquee', 6),
('certificat - mathematique economique', 1, 'Mathematiques pour economie', 6),
('certificat - mathematique informatique', 1, 'Mathematiques discretes', 6),
('licence pro - mathematique appliquee', 1, 'Mathematiques professionnelles', 6),
('licence pro - statistiques', 1, 'Statistiques appliquees', 6),
('licence pro - calcul scientifique', 1, 'Calcul scientifique avance', 6),
('formation courte - mathematique de base', 1, 'Bases mathematiques', 6),
('formation courte - algebre lineaire', 1, 'Algebre lineaire', 6),

-- ================= INFORMATIQUE (29) =================
('1 year licence - informatique generale', 2, 'Bases de linformatique', 6),
('1 year licence - programmation', 2, 'Programmation generale', 6),
('1 year licence - algorithmique', 2, 'Algorithmique de base', 6),
('1 year licence - systemes informatiques', 2, 'Systemes informatiques', 6),
('2 year licence - genie logiciel', 2, 'Developpement logiciel', 6),
('2 year licence - bases de donnees', 2, 'Bases de donnees relationnelles', 6),
('2 year licence - reseaux informatiques', 2, 'Reseaux et communications', 6),
('2 year licence - systemes exploitation', 2, 'Systemes dexploitation', 6),
('3 year licence - informatique avancee', 2, 'Informatique avancee', 6),
('3 year licence - developpement web', 2, 'Technologies web', 6),
('3 year licence - securite informatique', 2, 'Securite des systemes', 6),
('master - intelligence artificielle', 2, 'IA et machine learning', 6),
('master - data science', 2, 'Science des donnees', 6),
('master - cloud computing', 2, 'Technologies cloud', 6),
('master - cybersecurite', 2, 'Cybersecurite avancee', 6),
('doctorat - informatique', 2, 'Recherche informatique', 6),
('doctorat - intelligence artificielle', 2, 'Recherche en IA', 6),
('doctorat - reseaux', 2, 'Recherche reseaux', 6),
('certificat - programmation python', 2, 'Python avance', 6),
('certificat - java', 2, 'Programmation Java', 6),
('certificat - developpement mobile', 2, 'Applications mobiles', 6),
('licence pro - informatique appliquee', 2, 'Informatique professionnelle', 6),
('licence pro - reseaux', 2, 'Administration reseaux', 6),
('licence pro - developpement web', 2, 'Web avance', 6),
('formation courte - bureautique', 2, 'Outils bureautiques', 6),
('formation courte - maintenance informatique', 2, 'Maintenance systemes', 6),
('formation courte - programmation C', 2, 'Langage C', 6),
('formation courte - SQL', 2, 'Bases SQL', 6),
('formation courte - linux', 2, 'Administration Linux', 6),

-- ================= PHYSIQUE (28) =================
('1 year licence - physique generale', 3, 'Bases de la physique', 6),
('1 year licence - mecanique', 3, 'Mecanique classique', 6),
('1 year licence - thermodynamique', 3, 'Thermodynamique', 6),
('2 year licence - electromagnetisme', 3, 'Champs electromagnetiques', 6),
('2 year licence - optique', 3, 'Optique physique', 6),
('2 year licence - physique quantique', 3, 'Physique quantique', 6),
('3 year licence - physique avancee', 3, 'Physique avancee', 6),
('3 year licence - physique nucleaire', 3, 'Physique nucleaire', 6),
('master - physique appliquee', 3, 'Physique appliquee', 6),
('master - nanotechnologie', 3, 'Nanosciences', 6),
('master - physique des materiaux', 3, 'Materiaux avances', 6),
('doctorat - physique', 3, 'Recherche en physique', 6),
('doctorat - physique nucleaire', 3, 'Recherche nucleaire', 6),
('certificat - physique industrielle', 3, 'Physique industrielle', 6),
('certificat - metrologie', 3, 'Mesures physiques', 6),
('licence pro - physique appliquee', 3, 'Physique pro', 6),
('licence pro - instrumentation', 3, 'Instrumentation scientifique', 6),
('formation courte - mecanique des fluides', 3, 'Fluides', 6),
('formation courte - acoustique', 3, 'Acoustique', 6),
('formation courte - physique medicale', 3, 'Physique medicale', 6),
('formation courte - energie renouvelable', 3, 'Energies renouvelables', 6),
('formation courte - optoelectronique', 3, 'Optoelectronique', 6),
('formation courte - physique numerique', 3, 'Simulation numerique', 6),
('formation courte - astronomie', 3, 'Astronomie', 6),
('formation courte - physique solaire', 3, 'Physique solaire', 6),
('formation courte - radiophysique', 3, 'Radiophysique', 6),
('formation courte - physique atomique', 3, 'Physique atomique', 6),
('formation courte - capteurs physiques', 3, 'Capteurs', 6),

-- ================= CHIMIE (28) =================
('1 year licence - chimie generale', 4, 'Bases de la chimie', 6),
('1 year licence - chimie organique', 4, 'Chimie organique', 6),
('1 year licence - chimie minerale', 4, 'Chimie minerale', 6),
('2 year licence - chimie analytique', 4, 'Analyse chimique', 6),
('2 year licence - biochimie', 4, 'Biochimie', 6),
('2 year licence - physico-chimie', 4, 'Physico-chimie', 6),
('3 year licence - chimie appliquee', 4, 'Chimie appliquee', 6),
('3 year licence - chimie industrielle', 4, 'Chimie industrielle', 6),
('master - chimie des materiaux', 4, 'Materiaux chimiques', 6),
('master - chimie environnementale', 4, 'Environnement', 6),
('master - chimie pharmaceutique', 4, 'Pharmacie', 6),
('doctorat - chimie', 4, 'Recherche chimique', 6),
('doctorat - chimie organique', 4, 'Recherche organique', 6),
('certificat - chimie alimentaire', 4, 'Agroalimentaire', 6),
('certificat - controle qualite', 4, 'Qualite chimique', 6),
('licence pro - chimie appliquee', 4, 'Chimie professionnelle', 6),
('licence pro - chimie industrielle', 4, 'Industrie chimique', 6),
('formation courte - chimie verte', 4, 'Chimie durable', 6),
('formation courte - formulation chimique', 4, 'Formulation', 6),
('formation courte - laboratoire chimique', 4, 'Techniques labo', 6),
('formation courte - analyse spectrale', 4, 'Spectroscopie', 6),
('formation courte - chromatographie', 4, 'Chromatographie', 6),
('formation courte - toxicologie', 4, 'Toxicologie', 6),
('formation courte - chimie cosmetique', 4, 'Cosmetique', 6),
('formation courte - chimie petroliere', 4, 'Petrochimie', 6),
('formation courte - chimie des polymères', 4, 'Polymères', 6),
('formation courte - chimie nucleaire', 4, 'Chimie nucleaire', 6),
('formation courte - chimie analytique avancee', 4, 'Analyse avancee', 6);

INSERT INTO formations (name, department_id, description, duration_months) VALUES
('1 year licence - biologie generale', 5, 'Bases de la biologie', 6),
('1 year licence - biologie cellulaire', 5, 'Cellules et tissus', 6),
('1 year licence - biologie vegetale', 5, 'Plantes et vegetaux', 6),
('2 year licence - biologie animale', 5, 'Faune et organismes', 6),
('2 year licence - microbiologie', 5, 'Micro-organismes', 6),
('2 year licence - genetique', 5, 'Bases de la genetique', 6),
('3 year licence - biologie appliquee', 5, 'Applications biologiques', 6),
('3 year licence - biochimie', 5, 'Biochimie avancee', 6),
('master - biologie moleculaire', 5, 'ADN et biologie moleculaire', 6),
('master - biotechnologie', 5, 'Biotechnologies modernes', 6),
('master - biologie environnementale', 5, 'Biologie et environnement', 6),
('doctorat - biologie', 5, 'Recherche en biologie', 6),
('doctorat - biologie cellulaire', 5, 'Recherche cellulaire', 6),
('certificat - ecologie', 5, 'Ecologie appliquee', 6),
('certificat - parasitologie', 5, 'Etude des parasites', 6),
('licence pro - biologie appliquee', 5, 'Biologie professionnelle', 6),
('licence pro - analyses biologiques', 5, 'Analyses biologiques', 6),
('formation courte - laboratoire biologique', 5, 'Techniques de laboratoire', 6),
('formation courte - immunologie', 5, 'Systeme immunitaire', 6),
('formation courte - biologie medicale', 5, 'Biologie medicale', 6),
('formation courte - culture cellulaire', 5, 'Culture cellulaire', 6),
('formation courte - histologie', 5, 'Histologie', 6),
('formation courte - zoologie', 5, 'Zoologie', 6),
('formation courte - botanique', 5, 'Botanique', 6),
('formation courte - bioinformatique', 5, 'Biologie et informatique', 6),
('formation courte - neurobiologie', 5, 'Neurosciences', 6),
('formation courte - biologie marine', 5, 'Biologie marine', 6),
('formation courte - toxicologie biologique', 5, 'Toxicologie', 6);

INSERT INTO formations (name, department_id, description, duration_months) VALUES
('1 year licence - geologie generale', 6, 'Bases de la geologie', 6),
('1 year licence - mineralogie', 6, 'Mineraux et roches', 6),
('1 year licence - petrologie', 6, 'Etude des roches', 6),
('2 year licence - geologie structurale', 6, 'Structures geologiques', 6),
('2 year licence - geochimie', 6, 'Chimie de la Terre', 6),
('2 year licence - geomorphologie', 6, 'Formes du relief', 6),
('3 year licence - geologie appliquee', 6, 'Applications geologiques', 6),
('3 year licence - geologie miniere', 6, 'Mines et ressources', 6),
('master - geologie des ressources', 6, 'Gestion des ressources', 6),
('master - geologie environnementale', 6, 'Geologie et environnement', 6),
('master - hydrogeologie', 6, 'Eaux souterraines', 6),
('doctorat - geologie', 6, 'Recherche en geologie', 6),
('doctorat - geophysique', 6, 'Recherche geophysique', 6),
('certificat - cartographie geologique', 6, 'Cartographie', 6),
('certificat - risques naturels', 6, 'Risques geologiques', 6),
('licence pro - geologie appliquee', 6, 'Geologie professionnelle', 6),
('licence pro - exploration miniere', 6, 'Exploration des mines', 6),
('formation courte - geotechnique', 6, 'Geotechnique', 6),
('formation courte - sedimentologie', 6, 'Sediments', 6),
('formation courte - volcanologie', 6, 'Volcans', 6),
('formation courte - sismologie', 6, 'Seismes', 6),
('formation courte - paleontologie', 6, 'Fossiles', 6),
('formation courte - geologie marine', 6, 'Milieu marin', 6),
('formation courte - tectonique des plaques', 6, 'Tectonique', 6),
('formation courte - geophysique appliquee', 6, 'Geophysique', 6),
('formation courte - geologie petroliere', 6, 'Petrole et gaz', 6),
('formation courte - sols et pedologie', 6, 'Etude des sols', 6),
('formation courte - exploration geothermique', 6, 'Geothermie', 6),
('formation courte - SIG geologique', 6, 'Systemes dinformation geographique', 6);

INSERT INTO formations (name, department_id, description, duration_months) VALUES
('1 year licence - geographie generale', 7, 'Bases de la geographie', 6),
('1 year licence - geographie physique', 7, 'Geographie naturelle', 6),
('1 year licence - geographie humaine', 7, 'Societes et territoires', 6),
('2 year licence - cartographie', 7, 'Cartes et representations', 6),
('2 year licence - climatologie', 7, 'Climats et atmospheres', 6),
('2 year licence - hydrologie', 7, 'Eaux et bassins', 6),
('3 year licence - geographie appliquee', 7, 'Geographie appliquee', 6),
('3 year licence - amenagement du territoire', 7, 'Amenagement spatial', 6),
('master - amenagement urbain', 7, 'Urbanisme', 6),
('master - geographie environnementale', 7, 'Geographie durable', 6),
('master - SIG et cartographie', 7, 'Systemes dinformation geographique', 6),
('doctorat - geographie', 7, 'Recherche geographique', 6),
('doctorat - amenagement du territoire', 7, 'Recherche en amenagement', 6),
('certificat - urbanisme', 7, 'Urbanisme applique', 6),
('certificat - gestion des territoires', 7, 'Gestion territoriale', 6),
('licence pro - amenagement du territoire', 7, 'Amenagement professionnel', 6),
('licence pro - geographie appliquee', 7, 'Geographie professionnelle', 6),
('formation courte - SIG avance', 7, 'SIG avance', 6),
('formation courte - cartographie numerique', 7, 'Cartographie numerique', 6),
('formation courte - geographie rurale', 7, 'Espaces ruraux', 6),
('formation courte - geographie urbaine', 7, 'Villes et urbanisation', 6),
('formation courte - gestion environnementale', 7, 'Gestion environnement', 6),
('formation courte - transport et mobilite', 7, 'Mobilite', 6),
('formation courte - analyse territoriale', 7, 'Analyse spatiale', 6),
('formation courte - developpement durable', 7, 'Durabilite', 6),
('formation courte - observation territoriale', 7, 'Observation des territoires', 6),
('formation courte - planification urbaine', 7, 'Planification', 6),
('formation courte - risques environnementaux', 7, 'Gestion des risques', 6),
('formation courte - politiques publiques territoriales', 7, 'Politiques publiques', 6);


-- insertion des salles
INSERT INTO salles (name, capacity, type) VALUES
('Amphi 1', 50, 'amphi'),
('Amphi 2', 50, 'amphi'),
('Amphi 3', 50, 'amphi'),
('Amphi 4', 50, 'amphi'),
('Amphi 5', 50, 'amphi'),
('Amphi 6', 50, 'amphi'),
('Amphi 7', 50, 'amphi'),
('Amphi 8', 50, 'amphi'),
('Amphi 9', 50, 'amphi'),
('Amphi 10', 50, 'amphi'),
('Amphi 11', 50, 'amphi'),
('Amphi 12', 50, 'amphi'),
('Amphi 13', 50, 'amphi'),
('Amphi 14', 50, 'amphi'),
('Amphi 15', 50, 'amphi'),
('Amphi 16', 50, 'amphi'),
('Amphi A', 60, 'amphi'),
('Amphi B', 60, 'amphi'),
('Amphi 100', 60, 'amphi'),
('Amphi 101', 60, 'amphi'),
('Class 400', 20, 'classroom'),
('Class 401', 20, 'classroom'),
('Class 402', 20, 'classroom'),
('Class 403', 20, 'classroom'),
('Class 404', 20, 'classroom'),
('Class 405', 20, 'classroom'),
('Class 406', 20, 'classroom'),
('Class 407', 20, 'classroom'),
('Class 408', 20, 'classroom'),
('Class 409', 20, 'classroom'),
('Class 410', 20, 'classroom'),
('Class 411', 20, 'classroom'),
('Class 412', 20, 'classroom'),
('Class 413', 20, 'classroom'),
('Class 414', 20, 'classroom'),
('Class 415', 20, 'classroom'),
('Class 416', 20, 'classroom'),
('Class 417', 20, 'classroom'),
('Class 418', 20, 'classroom'),
('Class 419', 20, 'classroom'),
('Class 420', 20, 'classroom'),
('Class 421', 20, 'classroom'),
('Class 422', 20, 'classroom'),
('Class 423', 20, 'classroom'),
('Class 424', 20, 'classroom'),
('Class 425', 20, 'classroom'),
('Class 426', 20, 'classroom'),
('Class 427', 20, 'classroom'),
('Class 428', 20, 'classroom'),
('Class 429', 20, 'classroom'),
('Class 430', 20, 'classroom'),
('Class 500', 20, 'classroom'),
('Class 501', 20, 'classroom'),
('Class 502', 20, 'classroom'),
('Class 503', 20, 'classroom'),
('Class 504', 20, 'classroom'),
('Class 505', 20, 'classroom'),
('Class 506', 20, 'classroom'),
('Class 507', 20, 'classroom'),
('Class 508', 20, 'classroom'),
('Class 509', 20, 'classroom'),
('Class 510', 20, 'classroom'),
('Class 511', 20, 'classroom'),
('Class 512', 20, 'classroom'),
('Class 513', 20, 'classroom'),
('Class 514', 20, 'classroom'),
('Class 515', 20, 'classroom'),
('Class 516', 20, 'classroom'),
('Class 517', 20, 'classroom'),
('Class 518', 20, 'classroom'),
('Class 519', 20, 'classroom'),
('Class 520', 20, 'classroom'),
('Bloc A - Class 1', 20, 'classroom'),
('Bloc A - Class 2', 20, 'classroom'),
('Bloc A - Class 3', 20, 'classroom'),
('Bloc A - Class 4', 20, 'classroom'),
('Bloc A - Class 5', 20, 'classroom'),
('Bloc A - Class 6', 20, 'classroom'),
('Bloc A - Class 7', 20, 'classroom'),
('Bloc A - Class 8', 20, 'classroom'),
('Bloc A - Class 9', 20, 'classroom'),
('Bloc A - Class 10', 20, 'classroom'),
('Bloc A - Class 11', 20, 'classroom'),
('Bloc A - Class 12', 20, 'classroom'),
('Bloc A - Class 13', 20, 'classroom'),
('Bloc A - Class 14', 20, 'classroom'),
('Bloc A - Class 15', 20, 'classroom'),
('Bloc A - Class 16', 20, 'classroom'),
('Bloc A - Class 17', 20, 'classroom'),
('Bloc A - Class 18', 20, 'classroom'),
('Bloc A - Class 19', 20, 'classroom'),
('Bloc A - Class 20', 20, 'classroom'),
('Bloc A - Class 21', 20, 'classroom'),
('Bloc A - Class 22', 20, 'classroom'),
('Bloc A - Class 23', 20, 'classroom'),
('Bloc A - Class 24', 20, 'classroom'),
('Bloc A - Class 25', 20, 'classroom'),
('Bloc A - Class 26', 20, 'classroom'),
('Bloc A - Class 27', 20, 'classroom'),
('Bloc A - Class 28', 20, 'classroom'),
('Bloc A - Class 29', 20, 'classroom'),
('Bloc A - Class 30', 20, 'classroom'),
('Bloc B - Class 1', 20, 'classroom'),
('Bloc B - Class 2', 20, 'classroom'),
('Bloc B - Class 3', 20, 'classroom'),
('Bloc B - Class 4', 20, 'classroom'),
('Bloc B - Class 5', 20, 'classroom'),
('Bloc B - Class 6', 20, 'classroom'),
('Bloc B - Class 7', 20, 'classroom'),
('Bloc B - Class 8', 20, 'classroom'),
('Bloc B - Class 9', 20, 'classroom'),
('Bloc B - Class 10', 20, 'classroom'),
('Bloc B - Class 11', 20, 'classroom'),
('Bloc B - Class 12', 20, 'classroom'),
('Bloc B - Class 13', 20, 'classroom'),
('Bloc B - Class 14', 20, 'classroom'),
('Bloc B - Class 15', 20, 'classroom'),
('Bloc B - Class 16', 20, 'classroom'),
('Bloc B - Class 17', 20, 'classroom'),
('Bloc B - Class 18', 20, 'classroom'),
('Bloc B - Class 19', 20, 'classroom'),
('Bloc B - Class 20', 20, 'classroom'),
('Bloc B - Class 21', 20, 'classroom'),
('Bloc B - Class 22', 20, 'classroom'),
('Bloc B - Class 23', 20, 'classroom'),
('Bloc B - Class 24', 20, 'classroom'),
('Bloc B - Class 25', 20, 'classroom'),
('Bloc B - Class 26', 20, 'classroom'),
('Bloc B - Class 27', 20, 'classroom'),
('Bloc B - Class 28', 20, 'classroom'),
('Bloc B - Class 29', 20, 'classroom'),
('Bloc B - Class 30', 20, 'classroom'),
('Bloc C - Class 1', 20, 'classroom'),
('Bloc C - Class 2', 20, 'classroom'),
('Bloc C - Class 3', 20, 'classroom'),
('Bloc C - Class 4', 20, 'classroom'),
('Bloc C - Class 5', 20, 'classroom'),
('Bloc C - Class 6', 20, 'classroom'),
('Bloc C - Class 7', 20, 'classroom'),
('Bloc C - Class 8', 20, 'classroom'),
('Bloc C - Class 9', 20, 'classroom'),
('Bloc C - Class 10', 20, 'classroom'),
('Bloc C - Class 11', 20, 'classroom'),
('Bloc C - Class 12', 20, 'classroom'),
('Bloc C - Class 13', 20, 'classroom'),
('Bloc C - Class 14', 20, 'classroom'),
('Bloc C - Class 15', 20, 'classroom'),
('Bloc C - Class 16', 20, 'classroom'),
('Bloc C - Class 17', 20, 'classroom'),
('Bloc C - Class 18', 20, 'classroom'),
('Bloc C - Class 19', 20, 'classroom'),
('Bloc C - Class 20', 20, 'classroom'),
('Bloc C - Class 21', 20, 'classroom'),
('Bloc C - Class 22', 20, 'classroom'),
('Bloc C - Class 23', 20, 'classroom'),
('Bloc C - Class 24', 20, 'classroom'),
('Bloc C - Class 25', 20, 'classroom'),
('Bloc C - Class 26', 20, 'classroom'),
('Bloc C - Class 27', 20, 'classroom'),
('Bloc C - Class 28', 20, 'classroom'),
('Bloc C - Class 29', 20, 'classroom'),
('Bloc C - Class 30', 20, 'classroom'),
('Bloc D - Class 1', 20, 'classroom'),
('Bloc D - Class 2', 20, 'classroom'),
('Bloc D - Class 3', 20, 'classroom'),
('Bloc D - Class 4', 20, 'classroom'),
('Bloc D - Class 5', 20, 'classroom'),
('Bloc D - Class 6', 20, 'classroom'),
('Bloc D - Class 7', 20, 'classroom'),
('Bloc D - Class 8', 20, 'classroom'),
('Bloc D - Class 9', 20, 'classroom'),
('Bloc D - Class 10', 20, 'classroom'),
('Bloc D - Class 11', 20, 'classroom'),
('Bloc D - Class 12', 20, 'classroom'),
('Bloc D - Class 13', 20, 'classroom'),
('Bloc D - Class 14', 20, 'classroom'),
('Bloc D - Class 15', 20, 'classroom'),
('Bloc D - Class 16', 20, 'classroom'),
('Bloc D - Class 17', 20, 'classroom'),
('Bloc D - Class 18', 20, 'classroom'),
('Bloc D - Class 19', 20, 'classroom'),
('Bloc D - Class 20', 20, 'classroom'),
('Bloc D - Class 21', 20, 'classroom'),
('Bloc D - Class 22', 20, 'classroom'),
('Bloc D - Class 23', 20, 'classroom'),
('Bloc D - Class 24', 20, 'classroom'),
('Bloc D - Class 25', 20, 'classroom'),
('Bloc D - Class 26', 20, 'classroom'),
('Bloc D - Class 27', 20, 'classroom'),
('Bloc D - Class 28', 20, 'classroom'),
('Bloc D - Class 29', 20, 'classroom'),
('Bloc D - Class 30', 20, 'classroom');

